name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.8
  firebase_core: 4.4.0
  cloud_firestore: 6.1.2
  firebase_analytics: ^12.1.2
  firebase_crashlytics: ^5.0.7
  firebase_auth: ^6.1.4
  google_sign_in: ^6.3.0
  connectivity_plus: ^7.0.0
  image_picker: ^1.2.1
  firebase_storage: ^13.0.6
  flutter_local_notifications: ^19.4.2
  url_launcher: ^6.3.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imagenes/equipo/
    - assets/logo recicladora.png
    - assets/logo icono.jpeg
    - assets/logo circular.jpeg
    - assets/logo 2 recicladora.png
